# Generated by Django 6.0 on 2025-12-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ("created_time",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_time",)},
        ),
    ]
