# Generated by Django 6.0 on 2025-12-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ("-created_time",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_time",)},
        ),
    ]
